import { useCallback, useEffect, useState } from 'react'
import { api } from '../services/apiClient.js'
import { EmptyState, ErrorBanner, LoadingState, Modal, PageHeading, StatusPill, formatDate, shortId } from '../components/UI.jsx'

export default function AssignmentsPage() {
  const [data, setData] = useState(null); const [error, setError] = useState(null); const [runId, setRunId] = useState(''); const [working, setWorking] = useState(false); const [editing, setEditing] = useState(null); const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setError(null); try { setData(await api.assignments({ limit: 100, offset: 0 })) } catch (err) { setError(err) } }, [])
  useEffect(() => { load() }, [load])
  const automatic = async (event) => { event.preventDefault(); setWorking(true); setError(null); setNotice(''); try { const result = await api.automaticAssignments(runId.trim()); setNotice(`${result.assignments.length} assignment(s) created; ${result.unassigned_prp_ids.length} PRP(s) unassigned.`); setRunId(''); load() } catch (err) { setError(err) } finally { setWorking(false) } }
  const cancel = async (id) => { if (!window.confirm('Cancel this assignment and release its resources?')) return; try { await api.cancelAssignment(id); load() } catch (err) { setError(err) } }
  return <><PageHeading eyebrow="Patrol allocation" title="Patrol assignments" description="Allocate available units and officers to approved PRPs, then monitor assignment status." actions={<button className="secondary-button" onClick={load}>Refresh</button>} /><ErrorBanner error={error} onRetry={load} />{notice && <div className="success-banner">{notice}<button onClick={() => setNotice('')}>×</button></div>}
    <form className="auto-assignment" onSubmit={automatic}><div><strong>Create automatic assignments</strong><span>Use an approved optimization run ID.</span></div><input value={runId} onChange={(e) => setRunId(e.target.value)} required placeholder="Optimization run UUID" pattern="[0-9a-fA-F-]{36}" /><button className="primary-button" disabled={working}>{working ? 'Allocating…' : 'Assign patrols'}</button></form>
    {!data ? <LoadingState /> : !data.items.length ? <EmptyState title="No patrol assignments" message="Approve a PRP run, ensure patrol resources are available, then create automatic assignments." /> : <section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Patrol / officer</th><th>Shift</th><th>PRP</th><th>Status</th><th /></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td><strong title={item.id}>{shortId(item.id)}</strong><small>{formatDate(item.assigned_at)}</small></td><td><span>Unit {shortId(item.patrol_unit_id)}</span><small>Officer {shortId(item.police_officer_id)}</small></td><td><span>{formatDate(item.shift_start)}</span><small>to {formatDate(item.shift_end)}</small></td><td><span title={item.prp_location_id}>{shortId(item.prp_location_id)}</span><small>{item.prp_location.latitude.toFixed(4)}, {item.prp_location.longitude.toFixed(4)}</small></td><td><StatusPill value={item.status} /></td><td className="row-actions"><button disabled={!['ASSIGNED','ACKNOWLEDGED'].includes(item.status)} onClick={() => setEditing(item)}>Override</button><button className="danger-link" disabled={['COMPLETED','CANCELLED'].includes(item.status)} onClick={() => cancel(item.id)}>Cancel</button></td></tr>)}</tbody></table></div><div className="pagination"><span>{data.total} total assignments</span></div></section>}
    {editing && <OverrideForm assignment={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load() }} />}
  </>
}
function OverrideForm({ assignment, onClose, onSaved }) {
  const [form, setForm] = useState({ patrol_unit_id: assignment.patrol_unit_id, police_officer_id: assignment.police_officer_id, prp_location_id: assignment.prp_location_id }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await api.overrideAssignment(assignment.id, form); onSaved() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <Modal title="Override patrol assignment" onClose={onClose}><form className="form-grid" onSubmit={submit}>{error && <div className="form-error full">{error}</div>}<label className="full">Patrol unit ID<input value={form.patrol_unit_id} onChange={(e) => setForm({ ...form, patrol_unit_id: e.target.value })} required /></label><label className="full">Police officer ID<input value={form.police_officer_id} onChange={(e) => setForm({ ...form, police_officer_id: e.target.value })} required /></label><label className="full">Approved/active PRP ID<input value={form.prp_location_id} onChange={(e) => setForm({ ...form, prp_location_id: e.target.value })} required /></label><p className="field-help full">Replacement resources must be available and free from overlapping shifts.</p><div className="form-actions full"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Apply override'}</button></div></form></Modal>
}
