import { useCallback, useEffect, useState } from 'react'
import { api } from '../services/apiClient.js'
import { EmptyState, ErrorBanner, LoadingState, Modal, PageHeading, StatusPill, formatDate } from '../components/UI.jsx'

const emptyForm = { crime_type: '', severity: 3, latitude: '', longitude: '', occurred_at: '', reported_at: '', ward: '', area: '', status: 'REPORTED' }
const toLocalInput = (value) => value ? new Date(value).toISOString().slice(0, 16) : ''
export default function CrimeManagementPage() {
  const [page, setPage] = useState(null); const [filters, setFilters] = useState({ crime_type: '', severity: '', status: '', area: '' }); const [offset, setOffset] = useState(0); const [error, setError] = useState(null); const [editing, setEditing] = useState(null); const [upload, setUpload] = useState(null)
  const load = useCallback(async () => { setError(null); try { setPage(await api.crimes({ ...filters, limit: 20, offset })) } catch (err) { setError(err) } }, [filters, offset])
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer) }, [load])
  const changeFilter = (event) => { setOffset(0); setFilters({ ...filters, [event.target.name]: event.target.value }) }
  const deactivate = async (id) => { if (!window.confirm('Deactivate this crime incident? The record will be retained.')) return; try { await api.deactivateCrime(id); load() } catch (err) { setError(err) } }
  return <><PageHeading eyebrow="Crime data" title="Incident registry" description="Create, validate, filter and retain the records that feed SafeZone risk analysis." actions={<><label className="secondary-button file-button">Upload CSV<input type="file" accept=".csv,text/csv" onChange={async (e) => { const file = e.target.files[0]; if (!file) return; try { setUpload(await api.importCrimes(file)); load() } catch (err) { setError(err) } e.target.value = '' }} /></label><button className="primary-button" onClick={() => setEditing(emptyForm)}>+ New incident</button></>} /><ErrorBanner error={error} onRetry={load} />
    {upload && <div className="import-report"><strong>CSV import complete</strong><span>{upload.accepted} accepted · {upload.duplicates.length} duplicates · {upload.rejected.length} rejected</span>{upload.rejected.length > 0 && <details><summary>Review rejected rows</summary>{upload.rejected.map((row) => <p key={`${row.row}-${row.reason}`}>Row {row.row}: {row.reason}</p>)}</details>}<button onClick={() => setUpload(null)}>×</button></div>}
    <section className="filter-bar"><label>Search type<input name="crime_type" value={filters.crime_type} onChange={changeFilter} placeholder="e.g. Theft" /></label><label>Severity<select name="severity" value={filters.severity} onChange={changeFilter}><option value="">All</option>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label>Status<select name="status" value={filters.status} onChange={changeFilter}><option value="">All</option>{['REPORTED','VERIFIED','CLOSED','DISMISSED'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Area<input name="area" value={filters.area} onChange={changeFilter} placeholder="Area" /></label><button className="text-button" onClick={() => { setFilters({ crime_type: '', severity: '', status: '', area: '' }); setOffset(0) }}>Clear</button></section>
    {!page ? <LoadingState /> : page.items.length === 0 ? <EmptyState title="No incidents found" message="Adjust the filters or create the first crime record." /> : <section className="table-panel"><div className="table-scroll"><table><thead><tr><th>Incident</th><th>Severity</th><th>Area</th><th>Occurred</th><th>Status</th><th /></tr></thead><tbody>{page.items.map((crime) => <tr key={crime.id}><td><strong>{crime.crime_type}</strong><small>{crime.id.slice(0, 8)}</small></td><td><span className={`severity-badge severity-${crime.severity}`}>{crime.severity}</span></td><td>{crime.area || crime.ward || '—'}</td><td>{formatDate(crime.occurred_at)}</td><td><StatusPill value={crime.status} /></td><td className="row-actions"><button onClick={() => setEditing({ ...crime, occurred_at: toLocalInput(crime.occurred_at), reported_at: toLocalInput(crime.reported_at) })}>Edit</button><button className="danger-link" onClick={() => deactivate(crime.id)}>Deactivate</button></td></tr>)}</tbody></table></div><div className="pagination"><span>Showing {offset + 1}–{Math.min(offset + 20, page.total)} of {page.total}</span><div><button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 20))}>Previous</button><button disabled={offset + 20 >= page.total} onClick={() => setOffset(offset + 20)}>Next</button></div></div></section>}
    {editing && <CrimeForm initial={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load() }} />}
  </>
}
function CrimeForm({ initial, onClose, onSaved }) {
  const [form, setForm] = useState(initial); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const edit = Boolean(initial.id)
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const payload = { crime_type: form.crime_type.trim(), severity: Number(form.severity), latitude: Number(form.latitude), longitude: Number(form.longitude), occurred_at: new Date(form.occurred_at).toISOString(), reported_at: new Date(form.reported_at).toISOString(), ward: form.ward.trim() || null, area: form.area.trim() || null, status: form.status }; try { edit ? await api.updateCrime(initial.id, payload) : await api.createCrime(payload); onSaved() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <Modal title={edit ? 'Edit crime incident' : 'Create crime incident'} onClose={onClose}><form className="form-grid" onSubmit={submit}>{error && <div className="form-error full">{error}</div>}<label className="full">Crime category<input value={form.crime_type} onChange={(e) => setForm({ ...form, crime_type: e.target.value })} required maxLength="120" /></label><label>Severity<select value={form.severity} onChange={(e) => setForm({ ...form, severity: e.target.value })}>{[1,2,3,4,5].map((n) => <option key={n}>{n}</option>)}</select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{['REPORTED','VERIFIED','CLOSED','DISMISSED'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Latitude<input type="number" step="any" min="-90" max="90" value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} required /></label><label>Longitude<input type="number" step="any" min="-180" max="180" value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} required /></label><label>Occurred at<input type="datetime-local" value={form.occurred_at} onChange={(e) => setForm({ ...form, occurred_at: e.target.value })} required /></label><label>Reported at<input type="datetime-local" value={form.reported_at} onChange={(e) => setForm({ ...form, reported_at: e.target.value })} required /></label><label>Ward<input value={form.ward || ''} onChange={(e) => setForm({ ...form, ward: e.target.value })} /></label><label>Area<input value={form.area || ''} onChange={(e) => setForm({ ...form, area: e.target.value })} /></label><div className="form-actions full"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save incident'}</button></div></form></Modal>
}
