import { useState } from 'react'
import { api } from '../services/apiClient.js'
import { ErrorBanner, PageHeading, StatusPill, formatDate, shortId } from '../components/UI.jsx'

const nowLocal = () => { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16) }
const laterLocal = () => { const date = new Date(Date.now() + 8 * 3600000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16) }
export default function OptimizationPage() {
  const [form, setForm] = useState({ start: nowLocal(), end: laterLocal(), patrols: 3, radius: 3000 }); const [input, setInput] = useState('{\n  "candidates": [],\n  "demand_points": []\n}'); const [run, setRun] = useState(null); const [error, setError] = useState(null); const [loading, setLoading] = useState(false)
  const generate = async (event) => { event.preventDefault(); setLoading(true); setError(null); try { const parsed = JSON.parse(input); if (!Array.isArray(parsed.candidates) || !Array.isArray(parsed.demand_points)) throw new Error('Input JSON must contain candidates and demand_points arrays.'); const result = await api.generatePrps({ candidates: parsed.candidates, demand_points: parsed.demand_points, available_patrol_count: Number(form.patrols), coverage_radius_meters: Number(form.radius), shift: { start: new Date(form.start).toISOString(), end: new Date(form.end).toISOString() } }); setRun(result); sessionStorage.setItem('safezone.last.proposed_prps', JSON.stringify(result.prp_locations || [])) } catch (err) { setError(err) } finally { setLoading(false) } }
  const action = async (kind) => { setLoading(true); setError(null); try { const result = kind === 'approve' ? await api.approvePrps(run.id) : await api.activatePrps(run.id); setRun(result); sessionStorage.setItem('safezone.last.proposed_prps', JSON.stringify(result.prp_locations || [])) } catch (err) { setError(err) } finally { setLoading(false) } }
  const result = run?.result
  return <><PageHeading eyebrow="Strategic positioning" title="Generate patrol response points" description="Configure the operational shift and solve for maximum unique weighted-risk coverage." /><ErrorBanner error={error} />
    <div className="optimization-layout"><form className="panel optimization-form" onSubmit={generate}><div className="panel-heading"><div><p className="eyebrow">RUN CONFIGURATION</p><h3>Optimization inputs</h3></div></div><div className="form-grid"><label>Shift starts<input type="datetime-local" value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })} required /></label><label>Shift ends<input type="datetime-local" value={form.end} onChange={(e) => setForm({ ...form, end: e.target.value })} required /></label><label>Available patrol units<input type="number" min="0" max="500" value={form.patrols} onChange={(e) => setForm({ ...form, patrols: e.target.value })} required /></label><label>Coverage radius (metres)<input type="number" min="1" value={form.radius} onChange={(e) => setForm({ ...form, radius: e.target.value })} required /></label><label className="full">Candidate and demand input JSON<textarea rows="12" value={input} onChange={(e) => setInput(e.target.value)} spellCheck="false" /></label><label className="secondary-button file-button full">Load optimizer JSON file<input type="file" accept="application/json,.json" onChange={async (e) => { if (e.target.files[0]) setInput(await e.target.files[0].text()) }} /></label><p className="field-help full">The backend currently requires Stage 7 candidate PRPs and Stage 6 weighted demand points. The dashboard passes these through unchanged and does not duplicate scoring logic.</p><button className="primary-button full" disabled={loading}>{loading ? 'Solving…' : 'Generate PRPs'}</button></div></form>
      <section className="panel result-panel"><div className="panel-heading"><div><p className="eyebrow">LATEST RESULT</p><h3>Coverage outcome</h3></div>{run && <StatusPill value={run.status} />}</div>{!run ? <div className="result-empty"><span>△</span><h3>No optimization run yet</h3><p>Provide validated optimizer inputs and generate a run to inspect coverage.</p></div> : <><div className="result-metrics"><div><span>Coverage</span><strong>{result?.coverage_percentage?.toFixed(1) ?? 0}%</strong></div><div><span>Covered risk</span><strong>{result?.covered_weighted_risk?.toFixed(3) ?? 0}</strong></div><div><span>Total risk</span><strong>{result?.total_weighted_risk?.toFixed(3) ?? 0}</strong></div></div><dl className="metadata"><div><dt>Run ID</dt><dd title={run.id}>{shortId(run.id)}</dd></div><div><dt>Solver</dt><dd>{result?.solver_status || '—'}</dd></div><div><dt>Selected PRPs</dt><dd>{run.prp_locations.length}</dd></div><div><dt>Generated</dt><dd>{formatDate(run.run_at)}</dd></div><div><dt>Solve time</dt><dd>{result ? `${result.metadata.solve_time_seconds.toFixed(3)} s` : '—'}</dd></div><div><dt>Uncovered high-risk</dt><dd>{result?.uncovered_high_risk_points?.length || 0}</dd></div></dl>{result?.uncovered_high_risk_points?.length > 0 && <details className="uncovered"><summary>Uncovered high-risk areas</summary>{result.uncovered_high_risk_points.map((point) => <p key={point.demand_id}>{point.demand_id} · risk {point.risk_weight}</p>)}</details>}<div className="form-actions"><button className="secondary-button" disabled={loading || !run.prp_locations.length || run.prp_locations.every((p) => p.status !== 'CANDIDATE')} onClick={() => action('approve')}>Approve PRPs</button><button className="primary-button" disabled={loading || !run.prp_locations.length || run.prp_locations.some((p) => p.status !== 'APPROVED')} onClick={() => action('activate')}>Activate deployment</button></div></>}</section></div>
  </>
}
